/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "2025-lae-42d-44d"
include("lesson02-reflect-kotlin")
include("lesson03-reflect-java")
include("lesson03-logger")
include("lesson03-domain-model")
include("lesson04-mapTo")
include("lesson08-microbenchmarking")
// include("lesson09-naive-mapper")
// include("lesson10-naive-mapper-recursive")
include("lesson11-naive-mapper-enhanced")
include("lesson11-JMH-microbench-mapper")
include("lesson22-metaprogramming-Class-File-API")
include("lesson23-metaprogramming-Mapper")
// include("lesson28-sequences")
include("lesson29-sequences-and-generators")
include("lesson32-suspend-functions")
include("lesson34-gc")