/*
 * This source file was generated by the Gradle 'init' task
 */
package pt.isel

import kotlin.reflect.KClass
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull


class PersonDto (
    val name: String,
    @Match(name = "country") val origin: String,
    val age: Int,
)

class AppTest {
    @Test fun `test mapping PersonDto to Person`(){
        val klassPfPerson: KClass<Person> = Person::class

        val dto = PersonDto("Ze Manel", "Portugal", 27)
        val person = dto.mapTo(Person::class)
        assertEquals(dto.name, person.name)
        assertEquals(dto.origin, person.country)
        assertEquals(0, person.id)
    }
}
